[package]
name = "ridgehacks-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
cpal = "0.15.2"
# crossbeam = "0.8.2"
# hound = "3.5.0"
pico-args = "0.5.0"
rand = "0.8.5"
# rustfft = "6.1.0"
# ureq = "2.6.2"
